# Namespace (optional)
apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
# Login Deployment + Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: login:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /api/auth/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/auth/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: login
  namespace: staging
spec:
  selector:
    app: login
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
# Matchmaker Deployment + Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmakerservice
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchmakerservice
  template:
    metadata:
      labels:
        app: matchmakerservice
    spec:
      containers:
      - name: matchmakerservice
        image: matchmakerservice:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /Match/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: matchmakerservice
  namespace: staging
spec:
  selector:
    app: matchmakerservice
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
# StoreService Deployment + Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storeservice
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storeservice
  template:
    metadata:
      labels:
        app: storeservice
    spec:
      containers:
      - name: storeservice
        image: storeservice:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: storeservice
  namespace: staging
spec:
  selector:
    app: storeservice
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
---
# PlayerInfoService Deployment + Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playerinfoservice
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playerinfoservice
  template:
    metadata:
      labels:
        app: playerinfoservice
    spec:
      containers:
      - name: playerinfoservice
        image: playerinfoservice:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: playerinfoservice
  namespace: staging
spec:
  selector:
    app: playerinfoservice
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
  type: ClusterIP
---
# GameServer Deployment + Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameserver
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gameserver
  template:
    metadata:
      labels:
        app: gameserver
    spec:
      containers:
      - name: gameserver
        image: gameserver:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: gameserver
  namespace: staging
spec:
  selector:
    app: gameserver
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
---
# RelayRouter Deployment + Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relayrouter
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relayrouter
  template:
    metadata:
      labels:
        app: relayrouter
    spec:
      containers:
      - name: relayrouter
        image: relayrouter:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5002
        env:
        - name: ASPNETCORE_URLS
          value: "http://0.0.0.0:5002"
        readinessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5002
          initialDelaySeconds: 10
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: relayrouter
  namespace: staging
spec:
  selector:
    app: relayrouter
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP
---
# Microclient as a Job (runs once)
apiVersion: batch/v1
kind: Job
metadata:
  name: microclient
  namespace: staging
spec:
  template:
    spec:
      containers:
      - name: microclient
        image: microclient:latest
        imagePullPolicy: Never
        command: ["/bin/sh", "-c", "dotnet MicroClient.dll"]
      restartPolicy: Never