apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
# Login Deployment + Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: login
          image: tornbjerg/login-system:1.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /api/auth/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/auth/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: login
  namespace: staging
spec:
  selector:
    app: login
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
# Matchmaker Deployment + Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmakerservice
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchmakerservice
  template:
    metadata:
      labels:
        app: matchmakerservice
    spec:
      containers:
        - name: matchmakerservice
          image: tornbjerg/matchmaker-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /Match/health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: matchmakerservice
  namespace: staging
spec:
  selector:
    app: matchmakerservice
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
# StoreService Deployment + Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storeservice
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storeservice
  template:
    metadata:
      labels:
        app: storeservice
    spec:
      containers:
        - name: storeservice
          image: tornbjerg/shop:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: storeservice
  namespace: staging
spec:
  selector:
    app: storeservice
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
---
# PlayerInfoService Deployment + Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playerinfoservice
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playerinfoservice
  template:
    metadata:
      labels:
        app: playerinfoservice
    spec:
      containers:
        - name: playerinfoservice
          image: tornbjerg/player-info:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: playerinfoservice
  namespace: staging
spec:
  selector:
    app: playerinfoservice
  ports:
    - name: http
      protocol: TCP
      port: 6000
      targetPort: 6000
  type: ClusterIP
---
# GameServer Deployment + Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameserver
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gameserver
  template:
    metadata:
      labels:
        app: gameserver
    spec:
      containers:
        - name: gameserver
          image: tornbjerg/game-server:1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: gameserver
  namespace: staging
spec:
  selector:
    app: gameserver
  ports:
    - name: http
      protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
---
# RelayRouter Deployment + Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relayrouter
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relayrouter
  template:
    metadata:
      labels:
        app: relayrouter
    spec:
      containers:
        - name: relayrouter
          image: tornbjerg/relay-router:1.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5002
          env:
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:5002"
          readinessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: relayrouter
  namespace: staging
spec:
  selector:
    app: relayrouter
  ports:
    - name: http
      protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP
---
# RabbitMQ Deployment + Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:4.2-management
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5672
            - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: staging
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: ClusterIP
---
# Relay Deployment + Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: relay
  template:
    metadata:
      labels:
        app: relay
    spec:
      containers:
        - name: relay
          image: tornbjerg/relay-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
            - containerPort: 52306
---
apiVersion: v1
kind: Service
metadata:
  name: relay
  namespace: staging
spec:
  selector:
    app: relay
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: udp
      protocol: TCP
      port: 52306
      targetPort: 52306
  type: ClusterIP
---
# Microclient as a Job
apiVersion: batch/v1
kind: Job
metadata:
  name: microclient
  namespace: staging
spec:
  template:
    spec:
      containers:
        - name: microclient
          image: tornbjerg/micro-client:1.0.3
          imagePullPolicy: IfNotPresent
          env:
            - name: LOGIN_URL
              value: http://login:8080/api/auth/health
            - name: MATCHMAKER_URL
              value: http://matchmakerservice:5000/Match/health
            - name: STORE_URL
              value: http://storeservice:8081/Store
            - name: PLAYER_URL
              value: http://playerinfoservice:6000/api/player
          command: ["/bin/sh", "-c", "sleep 10 && dotnet MicroClient.dll"]
      restartPolicy: Never
